; NSIS owns installer localization independently of the Electron application locale.
LangString INSTALLER_INSTALL ${LANG_ENGLISH} "Install now"
LangString INSTALLER_INSTALL 3082 "Instalar ahora"
LangString INSTALLER_FINISH ${LANG_ENGLISH} "Finish"
LangString INSTALLER_FINISH 3082 "Finalizar"
LangString INSTALLER_NATIVE_PROGRESS ${LANG_ENGLISH} "Preparing installation… %d%%"
LangString INSTALLER_NATIVE_PROGRESS 3082 "Preparando la instalación… %d%%"
LangString INSTALLER_PROGRESS_EXTRACT ${LANG_ENGLISH} "Extracting files… %d%%"
LangString INSTALLER_PROGRESS_EXTRACT 3082 "Extrayendo archivos… %d%%"
LangString INSTALLER_PROGRESS_COPY ${LANG_ENGLISH} "Installing files… %d%%"
LangString INSTALLER_PROGRESS_COPY 3082 "Instalando archivos… %d%%"
LangString INSTALLER_PROGRESS_REGISTER ${LANG_ENGLISH} "Finishing installation… %d%%"
LangString INSTALLER_PROGRESS_REGISTER 3082 "Finalizando la instalación… %d%%"
LangString INSTALLER_PROGRESS_CLEAN ${LANG_ENGLISH} "Cleaning temporary files… %d%%"
LangString INSTALLER_PROGRESS_CLEAN 3082 "Limpiando archivos temporales… %d%%"
LangString INSTALLER_CHOOSE_PATH ${LANG_ENGLISH} "Choose location"
LangString INSTALLER_CHOOSE_PATH 3082 "Elegir ubicación"
LangString INSTALLER_BROWSE ${LANG_ENGLISH} "Browse"
LangString INSTALLER_BROWSE 3082 "Examinar"
LangString INSTALLER_LAUNCH ${LANG_ENGLISH} "Launch now"
LangString INSTALLER_LAUNCH 3082 "Iniciar ahora"
LangString INSTALLER_LAUNCH_FAILED ${LANG_ENGLISH} "Helmcode could not be launched. Retry, or clear Launch now and close the installer."
LangString INSTALLER_LAUNCH_FAILED 3082 "No se pudo iniciar Helmcode. Inténtalo de nuevo, o desmarca Iniciar ahora y cierra el instalador."
LangString INSTALLER_UI_ERROR ${LANG_ENGLISH} "The installer could not initialize its window. Close it and try again."
LangString INSTALLER_UI_ERROR 3082 "El instalador no pudo inicializar su ventana. Ciérralo e inténtalo de nuevo."
LangString INSTALLER_THEME_ERROR ${LANG_ENGLISH} "Use /THEME=auto, /THEME=light or /THEME=dark."
LangString INSTALLER_THEME_ERROR 3082 "Usa /THEME=auto, /THEME=light o /THEME=dark."
LangString INSTALLER_FAILED ${LANG_ENGLISH} "Installation did not finish. Close this installer and retry. If the problem persists, download the installer again."
LangString INSTALLER_FAILED 3082 "La instalación no finalizó. Cierra este instalador e inténtalo de nuevo. Si el problema persiste, descarga el instalador de nuevo."
LangString INSTALLER_RUNNING ${LANG_ENGLISH} "Helmcode is running. Quit it from the system tray and try again."
LangString INSTALLER_RUNNING 3082 "Helmcode está en ejecución. Ciérralo desde la bandeja del sistema e inténtalo de nuevo."
LangString INSTALLER_PATH_INVALID ${LANG_ENGLISH} "Choose a full local folder path. Drive roots, system folders, links and special characters are not supported."
LangString INSTALLER_PATH_INVALID 3082 "Elige una ruta de carpeta local completa. No se admiten raíces de unidad, carpetas del sistema, enlaces ni caracteres especiales."
LangString INSTALLER_PATH_OWNERSHIP ${LANG_ENGLISH} "Choose an empty folder or the registered Helmcode installation folder."
LangString INSTALLER_PATH_OWNERSHIP 3082 "Elige una carpeta vacía o la carpeta de instalación registrada de Helmcode."
LangString INSTALLER_PATH_WRITABLE ${LANG_ENGLISH} "This location is not writable. Choose a folder available to the current user."
LangString INSTALLER_PATH_WRITABLE 3082 "Esta ubicación no tiene permisos de escritura. Elige una carpeta disponible para el usuario actual."
LangString INSTALLER_DISK_SPACE ${LANG_ENGLISH} "There is not enough free disk space. Choose another location."
LangString INSTALLER_DISK_SPACE 3082 "No hay suficiente espacio libre en disco. Elige otra ubicación."
LangString INSTALLER_PER_USER ${LANG_ENGLISH} "This installer supports the current user only. Uninstall the existing all-users installation first."
LangString INSTALLER_PER_USER 3082 "Este instalador solo admite el usuario actual. Desinstala primero la instalación existente para todos los usuarios."
LangString INSTALLER_EXTRACT_FAILED ${LANG_ENGLISH} "The application files could not be extracted."
LangString INSTALLER_EXTRACT_FAILED 3082 "No se pudieron extraer los archivos de la aplicación."
LangString INSTALLER_EXTRACT_HINT ${LANG_ENGLISH} "Security software may have blocked a file, or the disk may be full. Close this installer and try again. If it keeps failing, send us the error details below."
LangString INSTALLER_EXTRACT_HINT 3082 "Es posible que un software de seguridad haya bloqueado un archivo o que el disco esté lleno. Cierra este instalador e inténtalo de nuevo. Si sigue fallando, envíanos los detalles del error a continuación."
LangString INSTALLER_EXTRACT_COPY ${LANG_ENGLISH} "Copy error details"
LangString INSTALLER_EXTRACT_COPY 3082 "Copiar detalles del error"
LangString INSTALLER_EXTRACT_EXPAND ${LANG_ENGLISH} "Show details"
LangString INSTALLER_EXTRACT_EXPAND 3082 "Mostrar detalles"
LangString INSTALLER_EXTRACT_COLLAPSE ${LANG_ENGLISH} "Hide details"
LangString INSTALLER_EXTRACT_COLLAPSE 3082 "Ocultar detalles"
LangString INSTALLER_EXTRACT_SAVED ${LANG_ENGLISH} "The full report was saved to %s"
LangString INSTALLER_EXTRACT_SAVED 3082 "El informe completo se guardó en %s"
LangString INSTALLER_EXTRACT_UNSAVED ${LANG_ENGLISH} "The full report could not be saved. Use Copy error details to keep it."
LangString INSTALLER_EXTRACT_UNSAVED 3082 "No se pudo guardar el informe completo. Usa Copiar detalles del error para conservarlo."
LangString INSTALLER_EXTRACT_COPIED ${LANG_ENGLISH} "Error details were copied to the clipboard."
LangString INSTALLER_EXTRACT_COPIED 3082 "Los detalles del error se copiaron al portapapeles."
